# -*- coding: utf-8 -*-
"""images_to_pdf.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CDd4gOWXDfuwHB0ewbSr__U-gG1xKxp8
"""

pip install python-docx

from docx import Document
from docx.shared import Inches

def insert_images(doc, image_paths):
    for image_path in image_paths:

        image_name = image_path.split("\\")[-1]

        doc.add_page_break()
        doc.add_picture(image_path, width=Inches(6))
        doc.add_paragraph(image_name).alignment = 1

def main():
    doc = Document()


    image_paths = [
        "/content/adaptive_correlation_Heston_model.PNG",
        "/content/asset_price_in_heston_model.PNG",
        "/content/adaptive_correlation_Heston_model - Copy.PNG",
        "/content/adaptive_correlation_Heston_model.PNG",
        "/content/asset_price_in_heston_model - Copy.PNG",
        "/content/asset_price_in_heston_model.PNG",
        "/content/autoregressive_model - Copy.PNG",
        "/content/autoregressive_model.PNG",
        "/content/average_implied_volatility_for_call_option - Copy.PNG",
        "/content/average_implied_volatility_for_call_option.PNG",
        "/content/BlackS_choles_Implied_volatility - Copy.PNG",
        "/content/BlackS_choles_Implied_volatility.PNG",
        "/content/Black_scholes_equation - Copy.PNG",
        "/content/Black_scholes_equation.PNG",
        "/content/Black_Scholes_Merton - Copy.PNG",
        "/content/Black_Scholes_Merton.PNG",
        "/content/bls_price.PNG",
        "/content/call_put_spread.PNG",
        "/content/Change_in_Implied_Volatility_of_Nearest_Expired_Date_Call_Option_(T1).png",
        "/content/Chapter2_2.1_Model_free_term_structure_fitting_curve.PNG",
        "/content/Chapter2_2.2_Heston_and_CEV_IV_process.PNG",
        "/content/Chapter2_2.3_Heston_and_CEV_HSI_process_vs_HSI.PNG",
        "/content/Chapter3_3.1_Time_series_of_the_VHSI_and_the_HSI.PNG",
        "/content/Chapter3_3.2_CEV_implied_volatility_vs_Heston_implied_volatility.PNG",
        "/content/Chapter5_5.1_Result_of_Monte_Carlo_simulation.PNG",
        "/content/Chapter6_6.1_local_volatility_surface.PNG",
        "/content/Chapter6_6.2_Volatility_surface_by_traditional_local_volatility_model.PNG",
        "/content/Chapter6_6.3mean_reversion_local_volatility_model.PNG",
        "/content/Chapter8_8.1_The_mean_value_of_Monte_Carlo_simulation.PNG",
        "/content/Chapter8_8.2_Expected_Return_Analysis_of_Financial_Strategies.PNG",
        "/content/Chapter8_8.3_variance_of_expected_return.png",
        "/content/Chapter8_8.4_mean_value_ofvaR.PNG",
        "/content/Chapter9_9.1_The_Implied_volatility_16_14.PNG",
        "/content/Chapter9_9.2_The_Implied_volatility_10_29.PNG",
        "/content/Chapter9_9.3_The_implied_volatility_of_3_April_201_16_14_and_3_April_2012_10_29.PNG",
        "/content/Chapter9_9.4_The_HSI_IVP_IVC.PNG",
        "/content/Chapter9_9.5_The_HSI_and_DIF.PNG",
        "/content/Comparison_of_forecasting_power.PNG",
        "/content/conditional_Probability_Density_Function_for_Hedged_Future_Asset_Value.PNG",
        "/content/Conditional_Probability_Density_Function_for_Hedged_Future_Asset_Value_where_St_greater_than_equals_to_ X.PNG",
        "/content/Conditional_Value_at_Risk_for_Payoff.PNG",
        "/content/constant_elasticity_of_variance_price_process_model.PNG",
        "/content/custom_local_volatility_model.PNG",
        "/content/Custom_Stochastic_Price_Evolution_Formula.PNG",
        "/content/custom_weighted_least_square_error_function.PNG",
        "/content/CVaR_alpha_(payoff).PNG",
        "/content/Difference_in_Implied_Volatility_between_Call_and_Put_Options_at_Time.PNG",
        "/content/DIFt_based_Trend_Judgment_Model.PNG",
        "/content/dupire_equation.PNG",
        "/content/effect_of_Equations_for_betha_j_Critical_Points_in_phi.PNG",
        "/content/Error_Metric_with_Sum_of_Squares_and_Absolute_Differences.PNG",
        "/content/expected_payoff.PNG",
        "/content/Expected_pay_off.PNG",
        "/content/expected_return.PNG",
        "/content/Expected_Shortfall.PNG",
        "/content/fischer_transformation.PNG",
        "/content/fit_the_cube_function.PNG",
        "/content/Formula_for_Near_Term_Trend_Prediction_Rule_for_Increased_Implied_Volatility_(T1).PNG",
        "/content/geometric_brownian_motion.PNG",
        "/content/Geometric_Brownian_Motion_for_Asset_ Price.PNG",
        "/content/Geometric_Brownian_Motion_model.PNG",
        "/content/geometric_brownian_motion_with_drift_and_volatility.PNG",
        "/content/Geometric_Brownian_Motion_with_Variable_Exponent.PNG",
        "/content/gradient_of_the_error_for_function.PNG",
        "/content/Hedged_Asset_Value_Formula_with_Conditions..PNG",
        "/content/Hedged_Asset_Value_Formula_with_Conditions.PNG",
        "/content/Hedging Rate_for_Options_with_Exercise_Price.PNG",
        "/content/heston's_implied_volatility_stochastic_process.PNG",
        "/content/heston_european_option_pricing_equation.PNG",
        "/content/Heston_geometric_brownian_motion_with_drift_and_volatility.PNG",
        "/content/Heston_model.PNG",
        "/content/Heston_Model_Implied_Volatility_Update_Equation.PNG",
        "/content/Heston_Model_Stochastic_Differential_Equation.PNG",
        "/content/heston_stochastic_volatility_model.PNG",
        "/content/heston_stochastic_volatility_mode_2.PNG",
        "/content/heston_stochastic_volatility_process.PNG",
        "/content/implied_volatility.PNG",
        "/content/Implied_Volatility_Calculation.PNG",
        "/content/Implied_Volatility_Fitting.PNG",
        "/content/Implied_Volatility_Formula_with_Bond_and_Option_Pricing_Components.PNG",
        "/content/ip.PNG",
        "/content/ip2.PNG",
        "/content/ip3.PNG",
        "/content/Itos_Lemma_the_logarithmic_of_the_underlying_price.PNG",
        "/content/mean_absolute_error.PNG",
        "/content/mean_reversion_process_proof.PNG",
        "/content/Model_based_on_the_Dupire_1994_formula.PNG",
        "/content/model_free_implied_volatility.PNG",
        "/content/Model_Free_Implied_Volatility_Expectation.PNG",
        "/content/moneyness_implication_volatility_relationship.PNG",
        "/content/Near_Term_Option_Based_Trend_Prediction_Model..PNG",
        "/content/Near_Term_Trend_Prediction_Rule_for_Increased_Implied_Volatility_(T1).PNG",
        "/content/net_payoff_from_bull_call_spread_strategy.PNG",
        "/content/One_day_ahead_comparison.PNG",
        "/content/one_day_head_comparison.png",
        "/content/Option_Price_Equation_with_the_Black_Scholes_Model.PNG",
        "/content/Option_spread.PNG",
        "/content/Parameter_Optimization_for_Local_Volatility_Modeling.PNG",
        "/content/partialy_differentiated_squared_error_loss_function.PNG",
        "/content/Payoff_for_Bull_Call_Spread_Strategy.PNG",
        "/content/Payoff_when_ST_greater_than_Kc.PNG",
        "/content/Payoff_when_ST_less_than_equal_to_Kc.PNG",
        "/content/pearson's_correlation_coefficient.PNG",
        "/content/Piece_wise_Function_for_At_based_on_Option_Exercise_Price..PNG",
        "/content/Piece_wise_Function_for_At_based_on_Option_Exercise_Price.PNG",
        "/content/polynomial_regression.PNG",
        "/content/Prediction_Performance_Comparison_of_Regression_Models.PNG",
        "/content/Prediction_Performance_Comparison_of_Regression_Models_2.PNG",
        "/content/Premium_Earned_from_Selling_Call_Option_Formula.PNG",
        "/content/Price_Evolution_under_Stochastic_Volatility.PNG",
        "/content/probability_Density_Function_of_a_logarithm_of_asset.PNG",
        "/content/probability_Density_Function_of_a_log_normal_distribution.PNG",
        "/content/probability_density_function_of_the_logarithm_of_asset.PNG",
        "/content/Ranking_of_basic_style_by_VaR.PNG",
        "/content/report_img_1.PNG",
        "/content/Return_Ratio_for_the_Basic_Style_Part_of_the_Strategy.PNG",
        "/content/sepps_equation.PNG",
        "/content/Sepp_Local_Volatility.PNG",
        "/content/Sepp_Local_Volatility_based_on_dupireFormula.PNG",
        "/content/short_call_option.PNG",
        "/content/simple_regression.PNG",
        "/content/squared_error_loss_function.PNG",
        "/content/Stochastic_Asset_Price_Calculation.PNG",
        "/content/stochastic_integral.PNG",
        "/content/Stochastic_Volatility_Adjustment_Formula..PNG",
        "/content/Stock_Price_Evolution_under_Ito's_Interpretation.PNG",
        "/content/stock_price_increase.PNG",
        "/content/strike_price_difference_profit.PNG",
        "/content/The_result_of_using_option_strategies_for_arbitrage.PNG",
        "/content/updated_heston_geometric_brownian_motion_with_drift_and_volatility.PNG",
        "/content/value_at_risk.PNG",
        "/content/value_at_risk_for_pay_off.PNG",
        "/content/variance_of_var.PNG",
        "/content/volatility_of_volatility_computation.PNG",
        "/content/volatility_sde_in_heston_model.PNG",
        "/content/Weighted_Mean_Implied_Volatility_of_Call_Options.PNG",
        "/content/Weighted_Mean_Implied_Volatility_of_Call_Options_(IVPT).PNG",
        "/content/Weighted_Mean_Implied_Volatility_of_Pull_Options_(IVPT).PNG",
        "/content/Wiener_processes.PNG"
]




    insert_images(doc, image_paths)
    doc.save('/content/combined_images_3.docx')

if __name__ == "__main__":
    main()

